### ISSUE TITLE
Expose Cookies in the Fluent API

### ISSUE THREAD

**Issue by RickFrankel** [otavioalfenas/Scraping-Toolkit#3]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like that [...]

I would like that the AllCookies property is exposed from the HttpRequest class through a method in the HttpRequestFluent class.

Eg:  Add an AddCookie or .WithCookie method to the HttpRequestFluent class.

Currently to scape ASP.Net pages the site I'm posting to needs to have an ASP.NET Session Cookie passed to it as well, which I can retrieve from the response object but cannot pass in to subsequent requests.

**Describe alternatives you've considered**
I could use the HttpRequest class itself but it feels better to use the Fluent approach.

**Comment by otavioalfenas** [comment]
Thanks for reporting and updating including functionality
The component will be published on 9/3 on nugget.org

**Comment by otavioalfenas** [comment]
@RickFrankel  thank's for implement feature
